### ISSUE TITLE
Bug: Helm Chart - appVersion is broken

### ISSUE THREAD

**Issue by Obirah** [redhat-cop/patch-operator#16]
When including the Patch Operator Helm Chart v0.1.1 (not 0.1.1) from https://redhat-cop.github.io/patch-operator as a Sub-Chart, the Pod is not able to pull the image without overriding the default image tag, because its value is `0.1.1` instead of `v0.1.1` - this looks like the appVersion of the Helm chart is broken as the image tag default is determined by that.

**Comment by raffaelespazzoli** [comment]
can you test if the new release fixes the issue. We have fixed several issues with the helm chart.

**Comment by Obirah** [comment]
The new release unfortunately does not fix the issue.

The image (when no explicit tag is specified) looks like this:
`quay-remote.bahnhub.tech.rz.db.de/redhat-cop/patch-operator:0.1.2`

Whereas the expected image would be:
`quay-remote.bahnhub.tech.rz.db.de/redhat-cop/patch-operator:v0.1.2`

**Comment by davgordo** [comment]
The problem is reproducible with the following steps:

```
helm repo add patch-operator https://redhat-cop.github.io/patch-operator
helm repo update
helm install patch-operator patch-operator/patch-operator
```
I have an observation that I'm sure must be related to the problem. I'm seeing two charts published for each release [1] . One has a release number prefix `v`, and the other has no release prefix. I suspect that when the `helm install ...` command is executed the non-prefixed release version is chosen because it is first in the index [2].

Still tracking down the root cause for the duplicate charts, but I figured I'd at least share what I've identified so far.

[1] https://github.com/redhat-cop/patch-operator/tree/gh-pages/patch-operator
[2] https://github.com/redhat-cop/patch-operator/blob/gh-pages/index.yaml
